config/routes.rb
Rails.application.routes.draw do
  devise_for :staffs, controllers: {
    sessions:      'staffs/sessions',
    passwords:     'staffs/passwords',
    registrations: 'staffs/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }

  root to: 'homes#top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :games, only: [:new, :index, :show, :create, :destroy, :edit, :update]
  resources :recruits, only: [:new, :create, :index, :show, :destroy] do
    resource :reservations, only: [:create, :destroy]
  end
  resources :products, only: [:index, :show]
  # resources :users, only: [:show, :edit, :update, :index]
  get 'mypage' => 'users#mypage'
  patch 'mypage/profile_edit' => 'users#update'
  get 'mypage/profile_edit' => 'users#profile_edit'

  resources :cart_items, only: [:index, :create, :update, :destroy] do
    collection do
      delete 'destroy_all'
    end
  end


  resources :staffs, only: [:edit, :update, :index]
  namespace :staffs do
    resources :products
  end

  resources :tags, only: [:create, :destroy] do
    get 'games', to: 'games#search'
  end
  get 'games/add', to: 'games#add'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :recruits, dependent: :destroy
  has_many :reservations, dependent: :destroy
  has_many :cart_items, dependent: :destroy
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :password])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    mypage_path(current_user.id)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected
  def after_sign_in_path_for(resource)
    mypage_path(current_user.id)
  end
  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def mypage
    @user = current_user
  end
  
  def profile_edit
  end 

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to mypage_path
    end
  end
  def user_params
    params.require(:user).permit(
      :name, 
      :email,
      :tel,
      :postal,
      :address)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= form_with model: @user, url: mypage_profile_edit_path, local:true do |f| %>
  <h2>User info</h2>
  <div class="form-group h-adr" >
    <span class="p-country-name" style="display:none;">Japan</span>
    <dl>
      <dt>お名前</dt>
      <dd><%= f.text_field :name%></dd>
    </dl>
    <dl>
      <dt>メールアドレス</dt>
      <dd><%= f.email_field :email, autofocus: true, autocomplete: "email" %></dd>
    </dl>
     <dl>
      <dt>電話番号</dt>
      <dd><%= f.text_field :tel, autofocus: true, autocomplete: "tel" %></dd>
    </dl>
    <dl>
      <dt>郵便番号</dt>
      <dd><%= f.text_field :postal, autofocus: true, autocomplete: "postal", class: "p-postal-code" %></dd>
    </dl>
    <dl>
      <dt>住所</dt>
      <dd><%= f.text_field :address, autofocus: true, autocomplete: "address",class: "p-region p-locality p-street-address p-extended-address" %></dd>
    </dl>

    <%= f.submit '会員情報の編集' %>
  </div>
<% end %>

app/views/users/mypage.html.erb
<h1>マイページ</h1>
<%= link_to "会員情報の編集", mypage_profile_edit_path, method: :get %>

app/views/users/profile_edit.html.erb
<%= javascript_pack_tag 'user/profile_edit' %>
<div class="customer-info">
  <%= form_with model: current_user, url: mypage_profile_edit_path, local:true do |f| %>
    <h2>お客様情報</h2>
    <div class="form-group h-adr" >
      <span class="p-country-name" style="display:none;">Japan</span>
      <dl>
        <dt>お名前</dt>
        <dd>
          <div class="err-msg-name"></div>
          <%= f.text_field :name, autofocus: true, autocomplete: "name", placeholder: "お名前", id: "name", class: "form-control" %>
        </dd>
      </dl>
      <dl>
        <dt>メールアドレス</dt>
        <dd>
          <div class="err-msg-email"></div>
          <%= f.email_field :email, autocomplete: "email", placeholder: "メールアドレス", id: "email", class: "form-control"  %>
        </dd>
      </dl>
      <dl>
        <dt>電話番号</dt>
        <dd>
          <div class="err-msg-tel"></div>
          <%= f.text_field :tel, autocomplete: "tel", placeholder: "電話番号", id: "tel", class: "form-control" %>
        </dd>
      </dl>
      <dl>
        <dt>郵便番号</dt>
        <dd>
          <div class="err-msg-postal"></div>
          <%= f.text_field :postal, autocomplete: "postal-code", placeholder: "郵便番号", id: "postal", class: "form-control" %>
        </dd>
      </dl>
      <dl>
        <dt>住所</dt>
        <dd><%= f.text_field :address, autocomplete: "address",class: "p-region p-locality p-street-address p-extended-address", class: "form-control" %></dd>
      </dl>
      <%= f.submit '会員情報の編集', class: "btn" %>
    </div>
  <% end %>
</div>