config/routes.rb
Rails.application.routes.draw do
  devise_for :staffs, controllers: {
    sessions:      'staffs/sessions',
    passwords:     'staffs/passwords',
    registrations: 'staffs/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }

  root to: 'homes#top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :games, only: [:new, :index, :show, :create, :destroy, :edit, :update]
  resources :recruits, only: [:new, :create, :index, :show, :destroy] do
    resource :reservations, only: [:create, :destroy]
  end
  resources :products, only: [:index, :show]
  # resources :users, only: [:show, :edit, :update, :index]
  get 'mypage' => 'users#mypage'
  patch 'mypage/profile_edit' => 'users#update'
  get 'mypage/profile_edit' => 'users#profile_edit'

  resources :cart_items, only: [:index, :create, :update, :destroy] do
    collection do
      delete 'destroy_all'
    end
  end


  resources :staffs, only: [:edit, :update, :index]
  namespace :staffs do
    resources :products
  end

  resources :tags, only: [:create, :destroy] do
    get 'games', to: 'games#search'
  end
  get 'games/add', to: 'games#add'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :recruits, dependent: :destroy
  attachment :game_image
  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps


  def save_tag(sent_tags)
    # current_tags = self.tags.pluck(:tag_name) unless self.tags.nil?
    # old_tags = current_tags - sent_tags
    # new_tags = sent_tags - current_tags
    # old_tags.each do |old|
    #   self.tags.delete Tag.find_by(tag_name: old)
    # end
    # new_tags.each do |new|
      new_post_tag = Tag.find_or_create_by(tag_name: sent_tags)
      self.tags << new_post_tag
    # end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  attachment :image
  validates :name, presence: true
  validates :price, presence: true
  has_many :cart_items, dependent: :destroy
end

app/models/recruit.rb
class Recruit < ApplicationRecord
  belongs_to :user
  belongs_to :game
  has_many :reservations, dependent: :destroy

  
  def reservated_by?(user)
    reservations.where(user_id: user.id).exists?
  end
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :recruit
end

app/models/staff.rb
class Staff < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_maps, dependent: :destroy, foreign_key: 'tag_id'
  has_many :games, through: :tag_maps
  validates :tag_name, uniqueness: true
end

app/models/tag_map.rb
class TagMap < ApplicationRecord
  belongs_to :game
  belongs_to :tag

  validates :game_id, presence: true
  validates :tag_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :recruits, dependent: :destroy
  has_many :reservations, dependent: :destroy
  has_many :cart_items, dependent: :destroy
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def new
    @tag_list = Tag.all
    @game = Game.new
    @tag = Tag.new
  end
  def create
    @game = Game.new(game_params)
    tag_list = params[:game][:tag_name]

    @game.save
    @game.save_tag(tag_list)
    redirect_to game_path(@game.id)
  end
  def destroy
    game = Game.find(params[:id])
    game.destroy
    redirect_to games_path
  end
  def index
    @tag_list = Tag.all
    @games = Game.all
  end
  def show
    @game = Game.find(params[:id])
    @game_tags = @game.tags
  end
  def edit
    @game = Game.find(params[:id])
    render :edit    
  end
  def update
    @game = Game.find(params[:id])
    @game.update(game_params)
    redirect_to game_path(@game.id)
  end
  def search
    @tag = Tag.find(params[:tag_id])
    @games = @tag.games.all
  end
  def add
  end  
  private

  def game_params
    params.require(:game).permit(:game_image, :name, :body, :duration, :headcount, :level, :remarks)
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @products = Product.page(params[:page]).reverse_order.includes(:cart_items)
  end
  def about
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def create
    @tag = Tag.new(tag_params)
    @tag.save
    redirect_to new_game_path
  end
  def destroy
    tag = Tag.find(params[:id])
    tag.destroy
    redirect_to new_game_path
  end

  private
  
  def tag_params
    params.require(:tag).permit(:tag_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  # 商品ごとの合計価格
  def subtotal_price(item)
    quantities = item.quantity
    pricies = item.product.price
    subtotal_price = add_tax(pricies * quantities)
    return subtotal_price
  end
  
  # 商品全体の合計金額
  def total_price(items)
    total_price = items.pluck(:quantity, :price).sum{ |q, p| q * p }
    total_price = add_tax(total_price)
    return total_price
  end

  # 消費税を加えた商品価格
  def add_tax(price)
    taxed_price = (price * 1.10).round
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/recruits_helper.rb
module RecruitsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/edit.html.erb
<h1>ゲーム登録編集フォーム</h1>
<%= form_with model: @game, local:true do |f| %>
  <h4>画像</h4>
  <%= f.attachment_field :game_image %>
  <h4>タイトル</h4>
  <%= f.text_field :name %>
  <h4>説明</h4>
  <%= f.text_area :body %>
  <h4>所要時間</h4>
  <%= f.select :duration, options_for_select({ "軽量級（～30分）" => "light", "中量級（30～60分）" => "middle", "重量級（60分～）" => "heavy" }) %>
  <h4>人員</h4>
  <%= f.text_field :headcount %>
  <h4>難易度</h4>
  <%= f.text_field :level %>
  <h4>タグ</h4>
  <%= f.text_field :tag_name %>
  <%= f.submit '登録' %>
<% end %>

app/views/games/index.html.erb
  <% @tag_list.each do |list| %>
    <span>
      <%= link_to list.tag_name, tag_games_path(tag_id: list.id) %>
    </span>
  <% end %>
  <% @games.each do |game| %>
    <div>
      <%= link_to game.name, game_path(game.id) %>
    </div>
  <% end %>

app/views/games/new.html.erb
<h1>ゲーム登録フォーム</h1>
<%= form_with model: @game, local:true do |f| %>
  <h4>タイトル</h4>
  <%= f.text_field :name %>
  <h4>説明</h4>
  <%= f.text_area :body %>
  <h4>所要時間</h4>
  <%= f.select :duration, options_for_select({ "軽量級（～30分）" => "light", "中量級（30～60分）" => "middle", "重量級（60分～）" => "heavy" }) %>
  <h4>人員</h4>
  <%= f.text_field :headcount %>
  <h4>難易度</h4>
  <%= f.text_field :level %>
  <h4>タグ</h4>
  <%= f.text_field :tag_name %>
  <%= f.submit '登録' %>
<% end %>

app/views/games/search.html.erb
<% @games.each do |game| %>

  <%= link_to game.name, game_path(game.id) %>

<% end %>

app/views/games/show.html.erb
<div>
  <%= attachment_image_tag @game, :game_image, :fill, 300, 300 %>
  <p>ゲーム名：<%= @game.name %></p>
  <p>説明：<%= @game.body %></p>
  <p>所要時間：<%= @game.duration %></p>
  <p>人数：<%= @game.headcount %></p>
  <p>難易度：<%= @game.level %></p>
  <p>タグ：</p>
  <% @game_tags.each do |tag| %>
    <span>
      <%= link_to tag.tag_name, tag_games_path(tag_id: tag.id) %>
    </span>
  <% end %>
  <%= link_to "Edit", edit_game_path(@game.id) %>
  <%= link_to "Destroy", game_path(@game.id), method: :delete %>
</div>