config/routes.rb
Rails.application.routes.draw do
  devise_for :staffs, controllers: {
    sessions:      'staffs/sessions',
    passwords:     'staffs/passwords',
    registrations: 'staffs/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }

  root to: 'homes#top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :games, only: [:new, :index, :show, :create, :destroy, :edit, :update]
  resources :recruits, only: [:new, :create, :index, :show, :destroy] do
    resource :reservations, only: [:create, :destroy]
  end
  resources :products, only: [:index, :show]
  # resources :users, only: [:show, :edit, :update, :index]
  get 'mypage' => 'users#mypage'
  patch 'mypage/profile_edit' => 'users#update'
  get 'mypage/profile_edit' => 'users#profile_edit'

  resources :cart_items, only: [:index, :create, :update, :destroy] do
    collection do
      delete 'destroy_all'
    end
  end


  resources :staffs, only: [:edit, :update, :index]
  namespace :staffs do
    resources :products
  end

  resources :tags, only: [:create, :destroy] do
    get 'games', to: 'games#search'
  end
  get 'games/add', to: 'games#add'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :recruits, dependent: :destroy
  attachment :game_image
  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps


  def save_tag(sent_tags)
    # current_tags = self.tags.pluck(:tag_name) unless self.tags.nil?
    # old_tags = current_tags - sent_tags
    # new_tags = sent_tags - current_tags
    # old_tags.each do |old|
    #   self.tags.delete Tag.find_by(tag_name: old)
    # end
    # new_tags.each do |new|
      new_post_tag = Tag.find_or_create_by(tag_name: sent_tags)
      self.tags << new_post_tag
    # end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  attachment :image
  validates :name, presence: true
  validates :price, presence: true
  has_many :cart_items, dependent: :destroy
end

app/models/recruit.rb
class Recruit < ApplicationRecord
  belongs_to :user
  belongs_to :game
  has_many :reservations, dependent: :destroy

  
  def reservated_by?(user)
    reservations.where(user_id: user.id).exists?
  end
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :recruit
end

app/models/staff.rb
class Staff < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_maps, dependent: :destroy, foreign_key: 'tag_id'
  has_many :games, through: :tag_maps
  validates :tag_name, uniqueness: true
end

app/models/tag_map.rb
class TagMap < ApplicationRecord
  belongs_to :game
  belongs_to :tag

  validates :game_id, presence: true
  validates :tag_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :recruits, dependent: :destroy
  has_many :reservations, dependent: :destroy
  has_many :cart_items, dependent: :destroy
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :setup_cart_item!,except: [:index, :destroy_all]
  respond_to :html, :js

  def index
    @items = CartItem.includes(:product)
  end

  def create
    if @item.blank?
      @item = current_user.cart_items.new(item_params)
    else
      @item.quantity += params[:cart_item][:quantity].to_i
    end
    if @item.save
      @items = CartItem.includes(:product)
    end
  end

  def update
    @item.update(item_params)
    @items = CartItem.includes(:product)
  end

  def destroy
    @item.destroy
    @items = CartItem.includes(:product)
  end

  def destroy_all
    CartItem.destroy_all
    @items = CartItem.includes(:product)
  end


  private
  
  def setup_cart_item!
    @item = current_user.cart_items.find_by(product_id: params[:cart_item][:product_id])
  end

  def item_params
    params.require(:cart_item).permit(:product_id, :quantity)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def new
    @tag_list = Tag.all
    @game = Game.new
    @tag = Tag.new
  end
  def create
    @game = Game.new(game_params)
    tag_list = params[:game][:tag_name]

    @game.save
    @game.save_tag(tag_list)
    redirect_to game_path(@game.id)
  end
  def destroy
    game = Game.find(params[:id])
    game.destroy
    redirect_to games_path
  end
  def index
    @tag_list = Tag.all
    @games = Game.all
  end
  def show
    @game = Game.find(params[:id])
    @game_tags = @game.tags
  end
  def edit
    @game = Game.find(params[:id])
    render :edit    
  end
  def update
    @game = Game.find(params[:id])
    @game.update(game_params)
    redirect_to game_path(@game.id)
  end
  def search
    @tag = Tag.find(params[:tag_id])
    @games = @tag.games.all
  end
  def add
  end  
  private

  def game_params
    params.require(:game).permit(:game_image, :name, :body, :duration, :headcount, :level, :remarks)
  end


end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def create
    @tag = Tag.new(tag_params)
    @tag.save
    redirect_to new_game_path
  end
  def destroy
    tag = Tag.find(params[:id])
    tag.destroy
    redirect_to new_game_path
  end

  private
  
  def tag_params
    params.require(:tag).permit(:tag_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  # 商品ごとの合計価格
  def subtotal_price(item)
    quantities = item.quantity
    pricies = item.product.price
    subtotal_price = add_tax(pricies * quantities)
    return subtotal_price
  end
  
  # 商品全体の合計金額
  def total_price(items)
    total_price = items.pluck(:quantity, :price).sum{ |q, p| q * p }
    total_price = add_tax(total_price)
    return total_price
  end

  # 消費税を加えた商品価格
  def add_tax(price)
    taxed_price = (price * 1.10).round
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/recruits_helper.rb
module RecruitsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cart_items/_cartitem_delete.html.erb
<%= form_with model: item, method: :delete, local:false, class:"delete_form" do |f| %>
  <%= f.hidden_field :product_id, value: item.product_id %>
  <%= f.submit "削除", class: "delete_btn" %>
<% end %>

app/views/cart_items/_cartitem_list.html.erb
<div id="cart_item_wrapper">
  <% if !items.blank? %>
    <p>現在<%= @items.sum(:quantity) %>個の商品が入っています</p>
    <%= link_to "全削除", destroy_all_cart_items_path, method: :delete, remote: true, class: "btn" %>
    <ul>
      <% items.each do |item| %>
        <li id="cartitem_list_<%= item.id %>", class="item">
          <%= link_to product_path(item.product_id), method: :get, class: "item__link"  do %>
            <%= attachment_image_tag item.product, :image, class: "item__image" %><br>
          <% end %>
          <div class="item__caption">
            <a href="/products/<%= item.product_id %>", class="item__name"><%= item.product.name %></a>
            <div id="quantity_change_<%= item.id %>">
              <%= render 'quantity_change', item: item %>      
            </div>
            <div id="cartitem_delete">
              <%= render 'cartitem_delete', item: item %>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  <% else %>
    <p>現在、お客様のカートに商品はありません。</p>
  <% end %>
</div>

app/views/cart_items/_quantity_change.html.erb
<%= form_with model: item, local: false, id: "quantity_change_form" do |f| %>
  <%= f.hidden_field :product_id, value: item.product_id %>
  <%= f.select :quantity, options_for_select(1..10, {selected: item.quantity} ) %>
  <%= f.submit "数量の変更" %>
<% end %>
<p>個数：<%= item.quantity %></p>
<p>小計（<%= item.quantity %>個の商品）&yen<%= subtotal_price(item).to_s(:delimited) %></p>

app/views/cart_items/_total-price.html.erb
<h2>合計金額：&yen<%= total_price(items).to_s(:delimited) %></h2>

app/views/cart_items/create.js.erb
$('#wrapper').html("<%= j(render 'index', items: @items) %>");

app/views/cart_items/destroy.js.erb
$('#cartitem_list_<%= @item.id %>').remove();
$('#cartitem_totalprice').html("<%= j(render 'total-price', items: @items) %>");
$('#cart_item_wrapper').html("<%= j(render 'cartitem_list', items: @items) %>");

app/views/cart_items/destroy_all.js.erb
$('#cart_item_wrapper').html("<%= j(render 'cartitem_list', items: @items) %>");
$('#cartitem_totalprice').html("<%= j(render 'total-price', items: @items) %>");

app/views/cart_items/index.html.erb
<h3>カートの中身</h3>
<div id="wrapper">
  <div class="main-area">
    <%= render 'cartitem_list', items: @items %>
  </div>
  <div class="side-area">
    <div id="cartitem_totalprice">
      <%= render 'total-price', items: @items %>
    </div>
  </div>
</div>

app/views/cart_items/update.js.erb
$('#quantity_change_<%= @item.id %>').html("<%= j(render 'quantity_change', item: @item) %>");
$('#cartitem_totalprice').html("<%= j(render 'total-price', items: @items) %>");
$('#cart_item_wrapper').html("<%= j(render 'cartitem_list', items: @items) %>");